insert into public.jm_questions(id, commune_id, question, choices) values
(1, 'c-alle', 'Quel bourg d''Ajoie est desservi par les Chemins de fer du Jura et entouré de terres agricoles ?', array['Alle', 'Bure', 'Soubey']),
(2, 'c-basse-allaine', 'Quelle commune réunit notamment Buix, Courtemaîche et Montignez ?', array['Basse-Allaine', 'Haute-Ajoie', 'La Baroche']),
(3, 'c-basse-vendline', 'Quelle commune est née de la réunion de Bonfol et Beurnevésin ?', array['Basse-Vendline', 'Damphreux-Lugnez', 'Vendlincourt']),
(4, 'c-boncourt', 'Quel village-frontière du nord de l''Ajoie est relié au rail vers Delle ?', array['Boncourt', 'Fahy', 'Courchavon']),
(5, 'c-bure', 'Quel village agricole de Haute-Ajoie est connu pour sa place d''armes ?', array['Bure', 'Grandfontaine', 'Fahy']),
(6, 'c-clos-du-doubs', 'Quelle commune est organisée autour de Saint-Ursanne, cité médiévale emblématique du Jura ?', array['Clos du Doubs', 'Soubey', 'Saint-Brais']),
(7, 'c-coeuve', 'Quel village ajoulot est connu pour son château et ses lavoirs historiques ?', array['Cœuve', 'Cornol', 'Courchavon']),
(8, 'c-cornol', 'Quel village se trouve proche du Mont Terri ?', array['Cornol', 'Courgenay', 'Alle']),
(9, 'c-courchavon', 'Quel petit village se trouve dans la vallée de l''Allaine, entre Porrentruy et la frontière française ?', array['Courchavon', 'Courtedoux', 'Cœuve']),
(10, 'c-courgenay', 'Quel bourg d''Ajoie, desservi par le rail et l''A16, a une tradition microtechnique liée à l''horlogerie ?', array['Courgenay', 'Bure', 'Damphreux-Lugnez']),
(11, 'c-courtedoux', 'Quelle commune est connue pour les découvertes paléontologiques faites lors des travaux de l''A16 ?', array['Courtedoux', 'Boncourt', 'Bure']),
(12, 'c-damphreux-lugnez', 'Quelle commune issue d''une fusion est connue pour ses zones humides ?', array['Damphreux-Lugnez', 'Fahy', 'Courchavon']),
(13, 'c-fahy', 'Dans quel village de Haute-Ajoie, contre la France, l''agriculture côtoie-t-elle des activités industrielles ?', array['Fahy', 'Courgenay', 'Cœuve']),
(14, 'c-fontenais', 'Quelle commune voisine de Porrentruy comprend notamment Bressaucourt ?', array['Fontenais', 'Courtedoux', 'Courchavon']),
(15, 'c-grandfontaine', 'Quel village de Haute-Ajoie est marqué historiquement par le travail de la pierre ?', array['Grandfontaine', 'Fahy', 'Bure']),
(16, 'c-haute-ajoie', 'Dans quelle commune se trouvent les grottes de Réclère ?', array['Haute-Ajoie', 'Grandfontaine', 'Fahy']),
(17, 'c-la-baroche', 'Quelle commune réunit notamment Asuel, Charmoille, Miécourt et Pleujouse ?', array['La Baroche', 'Haute-Ajoie', 'Basse-Allaine']),
(18, 'c-porrentruy', 'Quelle ville est l''ancienne résidence des princes-évêques ?', array['Porrentruy', 'Courgenay', 'Saignelégier']),
(19, 'c-vendlincourt', 'Quel village d''Ajoie réunit scierie, mécanique de précision et héritage horloger ?', array['Vendlincourt', 'Alle', 'Cœuve']),
(20, 'c-boecourt', 'Quelle commune se trouve proche du nœud routier jurassien ?', array['Boécourt', 'Courtételle', 'Mettembert']),
(21, 'c-bourrignon', 'Quel village se trouve sur l''ancien passage vers Lucelle et les Rangiers ?', array['Bourrignon', 'Saulcy', 'Soyhières']),
(22, 'c-chatillon', 'Quelle petite commune est connue pour son célèbre chêne monumental ?', array['Châtillon', 'Mettembert', 'Movelier']),
(23, 'c-courchapoix', 'Quel village du Val Terbi est traversé par la Scheulte ?', array['Courchapoix', 'Courroux', 'Soyhières']),
(24, 'c-courrendlin', 'Quelle commune est marquée par le passé industriel de Choindez ?', array['Courrendlin', 'Courroux', 'Moutier']),
(25, 'c-courroux', 'Quelle grande commune de l''agglomération de Delémont se trouve dans la vallée de la Birse ?', array['Courroux', 'Develier', 'Courtételle']),
(26, 'c-courtetelle', 'Quelle commune de la vallée de la Sorne se trouve entre Delémont et Haute-Sorne ?', array['Courtételle', 'Develier', 'Rossemaison']),
(27, 'c-delemont', 'Quelle ville est la capitale du canton du Jura ?', array['Delémont', 'Porrentruy', 'Moutier']),
(28, 'c-develier', 'Quelle commune se trouve immédiatement à l''ouest de Delémont, sur le corridor de l''A16 ?', array['Develier', 'Rossemaison', 'Courroux']),
(29, 'c-ederswiler', 'Quelle commune jurassienne est essentiellement germanophone ?', array['Ederswiler', 'Movelier', 'Pleigne']),
(30, 'c-haute-sorne', 'Quelle commune comprend notamment Bassecourt, Courfaivre et Glovelier ?', array['Haute-Sorne', 'Courtételle', 'Val Terbi']),
(31, 'c-mervelier', 'Quel village se trouve au pied des reliefs menant au col du Schelten ?', array['Mervelier', 'Saulcy', 'Bourrignon']),
(32, 'c-mettembert', 'Quelle petite commune est installée sur les hauteurs au nord de Delémont, entre forêts et terres agricoles ?', array['Mettembert', 'Courtételle', 'Rossemaison']),
(33, 'c-movelier', 'Quel village élevé et boisé est proche du plateau de Pleigne ?', array['Movelier', 'Soyhières', 'Develier']),
(34, 'c-pleigne', 'Quelle commune de plateau comprend le secteur de Lucelle ?', array['Pleigne', 'Saulcy', 'Ederswiler']),
(35, 'c-rossemaison', 'Quelle commune est connue dans le Jura pour l''inline hockey ?', array['Rossemaison', 'Courtételle', 'Develier']),
(36, 'c-saulcy', 'Quel village de montagne du district de Delémont se trouve à plus de 900 m d''altitude ?', array['Saulcy', 'Movelier', 'Soyhières']),
(37, 'c-soyhieres', 'Quel village au nord de Delémont se trouve au pied des vestiges de son château ?', array['Soyhières', 'Châtillon', 'Courroux']),
(38, 'c-val-terbi', 'Quelle grande commune est organisée autour de Vicques ?', array['Val Terbi', 'Courchapoix', 'Mervelier']),
(39, 'c-lajoux', 'Quel village élevé des Franches-Montagnes, historiquement agricole, est aussi marqué par l''horlogerie et la mécanique ?', array['Lajoux', 'Les Enfers', 'Soubey']),
(40, 'c-le-bemont', 'Quelle petite commune du haut plateau est desservie par le train rouge des CJ ?', array['Le Bémont', 'Les Enfers', 'Lajoux']),
(41, 'c-le-noirmont', 'Quelle commune est connue pour sa clinique de réadaptation ?', array['Le Noirmont', 'Saignelégier', 'Les Bois']),
(42, 'c-les-bois', 'Quelle commune du haut plateau, proche de la France, est connue pour l''horlogerie et les sports d''hiver ?', array['Les Bois', 'Les Genevez', 'Saint-Brais']),
(43, 'c-les-breuleux', 'Quel bourg industriel des Franches-Montagnes, à plus de 1000 m, est associé à l''horlogerie et aux sports d''hiver ?', array['Les Breuleux', 'Soubey', 'Le Bémont']),
(44, 'c-les-enfers', 'Quelle très petite commune de montagne est caractérisée par ses fermes et ses pâturages boisés ?', array['Les Enfers', 'Saignelégier', 'Le Noirmont']),
(45, 'c-les-genevez', 'Quel village abrite le Musée rural jurassien ?', array['Les Genevez', 'Lajoux', 'Montfaucon']),
(46, 'c-montfaucon', 'Dans quelle commune se trouve la gare de Pré-Petitjean ?', array['Montfaucon', 'Saint-Brais', 'Muriaux']),
(47, 'c-muriaux', 'Quelle commune du plateau possède des vestiges castraux et une halte ferroviaire des CJ ?', array['Muriaux', 'Les Enfers', 'Lajoux']),
(48, 'c-saignelegier', 'Quelle commune accueille le Marché-Concours national de chevaux ?', array['Saignelégier', 'Le Noirmont', 'Montfaucon']),
(49, 'c-saint-brais', 'Quelle commune comprend la halte ferroviaire de Bollement ?', array['Saint-Brais', 'Soubey', 'Muriaux']),
(50, 'c-soubey', 'Quel petit village de la vallée du Doubs possède un ancien moulin hydroélectrique ?', array['Soubey', 'Saint-Brais', 'Les Enfers']),
(51, 'c-moutier', 'Quelle ville est devenue jurassienne en 2026 ?', array['Moutier', 'Courrendlin', 'Delémont'])
on conflict (id) do update set commune_id = excluded.commune_id, question = excluded.question, choices = excluded.choices;
